# Generated by Django 5.1.4 on 2025-01-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], default='', max_length=1)),
                ('telefone', models.CharField(max_length=11, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('historico_medico', models.CharField(blank=True, max_length=355)),
            ],
        ),
    ]
