# Generated by Django 5.1.4 on 2025-01-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='arquivo_medico',
            field=models.FileField(blank=True, default='-', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], default='M', max_length=1),
        ),
    ]
