# Generated by Django 5.1.4 on 2025-01-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_paciente_arquivo_medico_alter_paciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='historico_medico',
            field=models.TextField(),
        ),
    ]
